### PR TITLE
create ci.yml

### PR DESCRIPTION
**Pull request by jee7s**
Enables continuous integration on main and develop.

### CODE REVIEW

**Comment by jee7s** [comment]
Took a few tries to get paths and versions right, but this is now ready to go

**Comment by dawilson9** [comment]
Unlike JSON, YML supports comments so, on principle, I should complain and reject this since the added file provides absolutely no indication of what it is, what it does, who maintains it, where it came from, etc.

**Comment by jee7s** [comment]
@dawilson9 I believe I've addressed your concerns. I didn't specify a maintainer as we can do that through other means, like a CODEOWNERS file. I will shortly open PR #2  to create that.

**Review by dawilson9 — APPROVED** [review]
Approved.

**Pull request merged**
